FROM haproxy:1.7

MAINTAINER Theo Massard <massar_t@etna-alternance.net>

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
#COPY logs.sh /
#
#RUN apt-get update && apt-get install -y wget
#RUN wget -O /tmp/libestr http://libestr.adiscon.com/files/download/libestr-0.1.10.tar.gz \
#      && tar -xjC /tmp/libestr
#
#RUN ./tmp/libestr/configure --libdir=/usr/lib \
#      -- includedir=/usr/include \
#      && make -C /tmp/libestr \
#      && make -C /tmp/libestr install 
#
#RUN chmod +x /logs.sh && /logs.sh

